### ISSUE TITLE
nipy.github.com → nipy.github.io

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipy/nipy.github.io#75]
I suggest you change the name of this repository :
[nipy.github.com](https://nipy.github.com/) → [nipy.github.io](https://nipy.github.io/)

Perhaps even:
[nipy.github.com](https://nipy.github.com/) → [nipy.org](https://nipy.org/)

**Comment by effigies** [comment]
Done. I don't think moving to nipy.org would keep the auto-redirect from nipy.github.io.
